### PR TITLE
Fix the way that pseudo localization is handled

### PR DESCRIPTION
**Pull request by ehoogerbeets**
- added a layer of indirection locale maps to pseudo style which maps to pseudo implementation
- if pseudolocale is set to a string, that is the only pseudolocale and it is the debug pseudo
- if pseudolocale is set to an array, each entry in the array is a pseudo locale with its default style
- if pseudolocale is set to an object, each entry maps a locale to a style, which allows you to redefine how a particular locale is handled
- if pseudolocale is set to an empty string, array, or object, then all pseudos are turned off
- added Australian English spelling correction, which is mostly the same as British English with a small number of differences
- added lots of new documentation on pseudo locales
- added better escaping for HTML tags, XML tags, substitution parameters, etc. while pseudolocalizing so that only the text part of each string is pseudo localized

### CODE REVIEW

**Comment by gouniLee** [comment]
webOS defines followg 4 locales are pseudoLocale. It expects to generate all.
"pseudoLocale": ["zxx-XX", "zxx-Hans-XX", "zxx-Cyrl-XX", "zxx-Hebr-XX"],
but It generates one zxx only.

**Comment by ehoogerbeets** [comment]
@gouniLee The "pseudoLocale" setting only configures which locales should be considered pseudo locales. The actual set of locales that the loctool localizes to is in the settings.locales array. If "zxx-Hans-XX" isn't listed there, then the loctool will not produce that locale.

**Comment by gouniLee** [comment]
> @gouniLee The "pseudoLocale" setting only configures which locales should be considered pseudo locales. The actual set of locales that the loctool localizes to is in the settings.locales array. If "zxx-Hans-XX" isn't listed there, then the loctool will not produce that locale.

webOS defined the pseudo Locale as following iLib's pseudo list. and For QML apps, We had to generate resource output even pseudo Locale. ( we only enable `--pseudo` option for QML apps to generate pseudo strings) With these changes, I think there's no way to generate pseudo strings for QML apps..

**Comment by ehoogerbeets** [comment]
@gouniLee Try the pseudolocalization for the qml apps now

**Comment by gouniLee** [comment]
> @gouniLee Try the pseudolocalization for the qml apps now

I tried it. but it still the same.. only I can get zxx.ts. Here's command that I use
`node loctool.js -2 -x music/ -l "ko-KR" --pseudo`

**Comment by ehoogerbeets** [comment]
You are not listing the pseudo locales in the locales list. Try this:

`node loctool.js -2 -x music/ -l "ko-KR,zxx-XX,zxx-Hans-XX,zxx-Cyrl-XX,zxx-Hebr-XX" --pseudo`

**Comment by gouniLee** [comment]
> You are not listing the pseudo locales in the locales list. Try this:
> 
> `node loctool.js -2 -x music/ -l "ko-KR,zxx-XX,zxx-Hans-XX,zxx-Cyrl-XX,zxx-Hebr-XX" --pseudo`

The result is still same. Others locale resource are not generated.
I did some debug. and the problem is here.https://github.com/iLib-js/loctool/blob/nopseudo/lib/PseudoFactory.js#L95
We have four styles. should take care of them all. 
```
pseudoLocales
zxx-Cyrl-XX: "debug-cyrillic"
zxx-Hans-XX: "debug-asian"
zxx-Hebr-XX: "debug-rtl"
zxx-XX: "debug"
```
it takes `debug` only. 
pseudoLocales[targetLocale.getSpec()] : "zxx-XX"

**Comment by ehoogerbeets** [comment]
@gouniLee please check again. Now that all the plugins are fixed, the pseudo generation should work better.

**Comment by gouniLee** [comment]
> @gouniLee please check again. Now that all the plugins are fixed, the pseudo generation should work better.

If I modify my plugins change as following you did in other plugins, I've checked it works. fyi.https://github.com/iLib-js/ilib-loctool-webos-qml/compare/pseudo?expand=1, If it's correct, other webos plugins should be fixed too.

There's one thing that I  want to make sure of, Previously, my plugins check `pseudoLocale` value from the `project.json` config file to get pseuo locale list,  If we check the value of `project.settings.locale` for pseuo locale, `project.pseudoLocale` is useless?

**Comment by ehoogerbeets** [comment]
project.pseudoLocale used to be a string or an array. Now it can now be a string, an array, or an object. If it is a string, it names the locale that will be used for the "debug" style of pseudo. If it is an array, then all of the locales listed there will become pseudo locales with their default styles. (eg. zxx-Hans-XX will be the Chinese pseudo.) If it is an object, then the properties are locale specifiers and the values are the style of pseudo you want each of them to be, such as "english-british" or "debug-cyrillic". That is, it maps a locale specifier to a style of pseudo to use for that locale.

In loctool 3.0, you will be able to make a plugin that implements any type of pseudo style you want, and you will use the pseudoLocale setting to map locales to those pseudo styles.

The project.settings.locales lists out all of the locales you want to localize to. These are each passed to the pseudo factory to load the right code for pseudos if the locale is a pseudo locale. If it is not a pseudo locale, it just processes the locale normally using the translation set.

So the way you had the webos plugins before, it didn't work correctly. With your fix, it should start to work properly again. (Even without an update in the loctool itself.)

**Review by gouniLee — APPROVED** [review]
I have a further question, I think It'd be better to talk tomorrow. 
It works fine. I approve it

**Comment by gouniLee** [comment]
FYI. I'm sharing the webOS localization config info.

I wrote a `project.json` config file like this: https://www.webosose.org/docs/guides/development/localization/applying-localization/#preparing-a-configuration-file
It uses `pseuLocale` an array type.

and locale lists are in bb recipe. Within this list, it doesn't include any pseudo locale. something like: https://github.com/webosose/meta-webosose/blob/master/meta-webos/conf/distro/include/webos-localization-locales.inc

In the form written style above, I could generate pseudo translations so far.

**Pull request merged**
